//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SitemapReader
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EAPortal_SystemLeadEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EAPortal_SystemLeadEntities object using the connection string found in the 'EAPortal_SystemLeadEntities' section of the application configuration file.
        /// </summary>
        public EAPortal_SystemLeadEntities() : base("name=EAPortal_SystemLeadEntities", "EAPortal_SystemLeadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EAPortal_SystemLeadEntities object.
        /// </summary>
        public EAPortal_SystemLeadEntities(string connectionString) : base(connectionString, "EAPortal_SystemLeadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EAPortal_SystemLeadEntities object.
        /// </summary>
        public EAPortal_SystemLeadEntities(EntityConnection connection) : base(connection, "EAPortal_SystemLeadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="relativeUrl">No Metadata Documentation available.</param>
        /// <param name="htmlTxt">No Metadata Documentation available.</param>
        public int Article_AddContent(global::System.String relativeUrl, global::System.String htmlTxt)
        {
            ObjectParameter relativeUrlParameter;
            if (relativeUrl != null)
            {
                relativeUrlParameter = new ObjectParameter("RelativeUrl", relativeUrl);
            }
            else
            {
                relativeUrlParameter = new ObjectParameter("RelativeUrl", typeof(global::System.String));
            }
    
            ObjectParameter htmlTxtParameter;
            if (htmlTxt != null)
            {
                htmlTxtParameter = new ObjectParameter("HtmlTxt", htmlTxt);
            }
            else
            {
                htmlTxtParameter = new ObjectParameter("HtmlTxt", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("Article_AddContent", relativeUrlParameter, htmlTxtParameter);
        }

        #endregion

    }

    #endregion

    
}
